import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './medium.css'
import './regular.css'
import DddHeader from '@/components/Common/Header/DddHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='zh-cn'>
      <body className={inter.className}>
        <DddHeader></DddHeader>
        {children}
      </body>
    </html>
  )
}
